#!/bin/sh

MESSAGE=$(cat $1)
COMMITFORMAT="^#([0-9]+) (feat|fix|docs|style|refactor|test|chore|perf)(\([a-zA-Z]+\))?: [a-z][^\.\n]{1,98}(\n\n[a-z][^\.\n]{1,100})*(\n\n(#[A-Za-z]+.*)*)?$"
#COMMITFORMAT="^#([0-9]+) (feat|fix|docs|style|refactor|test|chore)(\((.*)\))?: (.*)$" 
#COMMITFORMAT="^(feat|fix|docs|style|refactor|test|chore)(\((.*)\))?: #([0-9]+) (.*)$"

if ! [[ "$MESSAGE" =~ $COMMITFORMAT ]]; then
  echo "Your commit was rejected due to the commit message. Skipping..." 
  echo ""
  echo "Please use the following format:"
  #echo "feat: #1234 feature example comment"
  echo "#1234 fix(ui): bugfix example comment"
  echo ""
  echo "More details on CONTRIBUTING.md"
  exit 1
fi

